language: php

sudo: false

php:
  - 7.2

install:
  - composer global require drupal/coder
  - export PATH="$HOME/.config/composer/vendor/bin:$PATH"
  - phpcs --config-set installed_paths ../../drupal/coder/coder_sniffer

script:
  - phpcs --standard=Drupal --extensions=php,inc ./
